"""Email notification service using Resend.

CRITICAL: This service must never crash the screening pipeline.
All public functions catch exceptions and log errors instead of raising.
"""

from __future__ import annotations

import logging
import os

logger = logging.getLogger(__name__)

RESEND_API_KEY = os.environ.get("RESEND_API_KEY")
ALERT_FROM_EMAIL = os.environ.get("ALERT_FROM_EMAIL", "SentinelSpace <alerts@sentinelspace.app>")


def is_configured() -> bool:
    """Return True if the email service has an API key configured."""
    return bool(RESEND_API_KEY)


def send_alert_email(to_email: str, subject: str, html_body: str) -> bool:
    """Send an alert email via Resend.

    Returns True on success, False on any failure.  Never raises.
    """
    if not RESEND_API_KEY:
        logger.debug("Email not configured (no RESEND_API_KEY)")
        return False

    try:
        import resend
        resend.api_key = RESEND_API_KEY

        resend.Emails.send({
            "from": ALERT_FROM_EMAIL,
            "to": [to_email],
            "subject": subject,
            "html": html_body,
        })
        logger.info("Alert email sent to %s: %s", to_email, subject)
        return True
    except Exception as e:
        logger.error("Failed to send email to %s: %s", to_email, e)
        return False


def format_alert_email(
    alert_message: str,
    threat_level: str,
    asset_name: str = "",
    frontend_url: str = "",
) -> tuple[str, str]:
    """Format an alert into an email subject and HTML body.

    Returns ``(subject, html_body)``.
    """
    subject = f"SentinelSpace Alert: {threat_level}"
    if asset_name:
        subject += f" — {asset_name}"

    level_colors = {
        "CRITICAL": "#FF1744",
        "HIGH": "#FF6D00",
        "MODERATE": "#FFD600",
        "LOW": "#00E676",
    }
    bg_color = level_colors.get(threat_level, "#888")
    text_on_bg = "white" if threat_level in ("CRITICAL", "HIGH") else "#0B1120"

    link_section = ""
    if frontend_url:
        link_section = (
            f'<p style="margin-top:16px;">'
            f'<a href="{frontend_url}" style="color:#2563EB;">View in SentinelSpace</a>'
            f'</p>'
        )

    html_body = f"""
    <div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px;margin:0 auto;">
        <div style="background:#0B1120;color:white;padding:16px 24px;border-radius:8px 8px 0 0;">
            <h2 style="margin:0;font-size:18px;">SentinelSpace Alert</h2>
        </div>
        <div style="background:#1A1F2E;color:#E5E7EB;padding:24px;border-radius:0 0 8px 8px;">
            <div style="background:{bg_color};color:{text_on_bg};padding:8px 16px;
                        border-radius:4px;display:inline-block;margin-bottom:16px;
                        font-weight:600;font-size:13px;">
                {threat_level}
            </div>
            <p style="font-size:14px;line-height:1.6;margin:0 0 12px;">{alert_message}</p>
            {link_section}
            <hr style="border-color:#2D3748;margin:16px 0;">
            <p style="font-size:12px;color:#9CA3AF;margin:0;">
                This alert was generated by SentinelSpace automated screening.
            </p>
        </div>
    </div>
    """
    return subject, html_body
