"""PDF report generation for SentinelSpace.

Generates conjunction summary reports, insurance risk reports,
and compliance reports using ReportLab.
"""

from __future__ import annotations

import io
import logging
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)


def generate_conjunction_report(
    assets: list[dict],
    conjunctions: list[dict],
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
) -> bytes:
    """Generate a conjunction summary PDF report.

    Returns PDF as bytes.
    """
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            PageBreak,
        )
    except ImportError:
        logger.warning("reportlab not installed, returning placeholder PDF")
        return _placeholder_pdf("Conjunction Summary Report")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        fontSize=24,
        textColor=HexColor("#0B1120"),
        spaceAfter=12,
    )
    elements.append(Paragraph("SentinelSpace", title_style))
    elements.append(Paragraph("Conjunction Assessment Report", styles["Title"]))
    elements.append(Spacer(1, 12))

    # Date range
    date_str = f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
    if start_date and end_date:
        date_str += f" | Period: {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}"
    elements.append(Paragraph(date_str, styles["Normal"]))
    elements.append(Spacer(1, 24))

    # Executive Summary
    elements.append(Paragraph("Executive Summary", styles["Heading2"]))
    total = len(conjunctions)
    critical = sum(1 for c in conjunctions if c.get("threat_level") == "CRITICAL")
    high = sum(1 for c in conjunctions if c.get("threat_level") == "HIGH")
    moderate = sum(1 for c in conjunctions if c.get("threat_level") == "MODERATE")
    low = sum(1 for c in conjunctions if c.get("threat_level") == "LOW")

    summary_text = (
        f"Total conjunction events: {total}<br/>"
        f"Critical: {critical} | High: {high} | Moderate: {moderate} | Low: {low}<br/>"
        f"Protected assets monitored: {len(assets)}"
    )
    elements.append(Paragraph(summary_text, styles["Normal"]))
    elements.append(Spacer(1, 16))

    # Conjunction table
    if conjunctions:
        elements.append(Paragraph("Conjunction Events", styles["Heading2"]))
        table_data = [["#", "Asset", "Threat Object", "TCA (UTC)", "Miss (m)", "Pc", "Level"]]
        for i, c in enumerate(conjunctions[:50], 1):
            pc = c.get("collision_probability", 0)
            pc_str = f"{pc:.2e}" if pc else "N/A"
            table_data.append([
                str(i),
                str(c.get("primary_asset_name", "Unknown")),
                str(c.get("secondary_name", c.get("secondary_norad_id", "Unknown"))),
                str(c.get("tca", ""))[:19],
                f"{c.get('miss_distance_m', 0):.0f}",
                pc_str,
                str(c.get("threat_level", "LOW")),
            ])

        table = Table(table_data, repeatRows=1)
        threat_colors = {
            "CRITICAL": HexColor("#FF1744"),
            "HIGH": HexColor("#FF6D00"),
            "MODERATE": HexColor("#FFD600"),
            "LOW": HexColor("#00E676"),
        }

        style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#0B1120")),
            ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#FFFFFF")),
            ("FONTSIZE", (0, 0), (-1, 0), 8),
            ("FONTSIZE", (0, 1), (-1, -1), 7),
            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#D4D4D4")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]

        # Color-code rows by threat level
        for i, c in enumerate(conjunctions[:50], 1):
            level = c.get("threat_level", "LOW")
            if level in threat_colors:
                style_commands.append(
                    ("TEXTCOLOR", (6, i), (6, i), threat_colors[level])
                )

        table.setStyle(TableStyle(style_commands))
        elements.append(table)

    elements.append(Spacer(1, 24))
    elements.append(Paragraph(
        "This report was generated by SentinelSpace - Space Debris Threat Assessment Platform",
        styles["Normal"],
    ))

    doc.build(elements)
    return buffer.getvalue()


def generate_insurance_report(asset: dict, history: list[dict]) -> bytes:
    """Generate an insurance risk assessment PDF."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    except ImportError:
        return _placeholder_pdf("Insurance Risk Report")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("SentinelSpace — Insurance Risk Assessment", styles["Title"]))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(f"Asset: {asset.get('name', 'Unknown')} (NORAD {asset.get('norad_id', 'N/A')})", styles["Heading2"]))
    elements.append(Spacer(1, 8))

    info = (
        f"Orbit type: {asset.get('orbit_type', 'N/A')}<br/>"
        f"Mass: {asset.get('mass_kg', 'N/A')} kg<br/>"
        f"Cross-section: {asset.get('cross_section_m2', 'N/A')} m²<br/>"
        f"Maneuverable: {'Yes' if asset.get('maneuverable') else 'No'}<br/>"
        f"Historical conjunctions: {len(history)}"
    )
    elements.append(Paragraph(info, styles["Normal"]))

    doc.build(elements)
    return buffer.getvalue()


def _placeholder_pdf(title: str) -> bytes:
    """Generate a minimal PDF when reportlab is unavailable."""
    content = f"""%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Resources<</Font<</F1 4 0 R>>>>>>endobj
4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj
xref
0 5
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
0000000266 00000 n
trailer<</Size 5/Root 1 0 R>>
startxref
339
%%EOF"""
    return content.encode("latin-1")
